name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install pinata-web3
          npm install node-fetch

      - name: Upload site to Pinata
        run: |
          node upload_site.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}


      - name: Upload site to Pinata
        run: |
          node upload_site.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
